[build]
  publish = "static"
  command = "echo 'No build needed'"

[dev]
  command = "flask run --host=0.0.0.0 --port=8888"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
